spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    