spring:
  application:
    name: ProductService
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    default: local
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"